### ISSUE TITLE
CreativeGates - Error on enable

### ISSUE THREAD

**Issue by Poweringg** [MassiveCraft/CreativeGates#124]
Error occurred while enabling CreativeGates v2.8.7Beta (Is it up to date?)
java.lang.NoClassDefFoundError: com/massivecraft/massivecore/command/MassiveCommandVersion
	at com.massivecraft.creativegates.CreativeGates.onEnableInner(CreativeGates.java:90) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:121) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[craftbukkit.jar:git-Spigot-944aa20-8d16fc0]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [craftbukkit.jar:git-Spigot-944aa20-8d16fc0]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-944aa20-8d16fc0]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [craftbukkit.jar:git-Spigot-944aa20-8d16fc0]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [craftbukkit.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [craftbukkit.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [craftbukkit.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [craftbukkit.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [craftbukkit.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [craftbukkit.jar:git-Spigot-944aa20-8d16fc0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
Caused by: java.lang.ClassNotFoundException: com.massivecraft.massivecore.command.MassiveCommandVersion
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[craftbukkit.jar:git-Spigot-944aa20-8d16fc0]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit.jar:git-Spigot-944aa20-8d16fc0]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_73]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_73]
	... 13 more

**Comment by magnusulf** [comment]
Use the same version of MassiveCore and CreativeGates.
