### ISSUE TITLE
Creativegates error occured

### ISSUE THREAD

**Issue by jessenjonas** [MassiveCraft/CreativeGates#134]
Hi i was just installing it, and i saw this error, can you help.

* CreativeGates version: 2.11.0
* MassiveCore version: 2.8.21
* Im using 1.11.2 craftbukkit
* Config pastebin:
[18:38:13 INFO]: [CreativeGates] Enabling CreativeGates v2.11.0
[18:38:13 INFO]: [CreativeGates 2.11.0] === ENABLE START ===
[18:38:13 ERROR]: Error occurred while enabling CreativeGates v2.11.0 (Is it up to date?)
java.lang.NoSuchMethodError: com.massivecraft.massivecore.AspectColl.get(Ljava/lang/Object;Z)Lcom/massivecraft/massivecore/store/EntityInternal;
        at com.massivecraft.creativegates.CreativeGates.onEnableInner(CreativeGates.java:65) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:75) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[craftbukkit.jar:git-Bukkit-6e3cec8]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit.jar:git-Bukkit-6e3cec8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:361) [craftbukkit.jar:git-Bukkit-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323) [craftbukkit.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:411) [craftbukkit.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:372) [craftbukkit.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:327) [craftbukkit.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:244) [craftbukkit.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:521) [craftbukkit.jar:git-Bukkit-6e3cec8]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by jessenjonas** [comment]
Found the problem, my massivecore wasn't updates.
