### ISSUE TITLE
1.13.2 Breaks CreativeGates "Create" function due to 1.13 blockid changes.

### ISSUE THREAD

**Issue by Xeddius** [MassiveCraft/CreativeGates#143]
Exactly as title says, 1.13+ breaks the "Create gate" ability because it can no longer recognize blockid's for the portal blocks. (eg, `emerald_block` is now `emeraldblock`, etc.) Though changing the config has yet to yield results. 

I will test further to see if I can find a workaround, as of now the only way to make gates is to load a 1.12.2 version of the server, create the gate, then run the 1.13.2 server after saving and closing the 1.12.2 server. It's tedious, but it works for the time being. 

(Fine if you're a server admin, but if users need the feature, either stay on 1.12.2 or do your best to get by without it in 1.13+ until there's a better solution.)

**Comment by Xeddius** [comment]
A detailed error is as follows:

`[16:44:02 ERROR]: Could not pass event PlayerInteractEvent to CreativeGates v2.14.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[Paper.jar:git-Paper-455]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[Paper.jar:git-Paper-455]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Paper.jar:git-Paper-455]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[Paper.jar:git-Paper-455]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:314) ~[Paper.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:465) ~[Paper.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1359) ~[Paper.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[Paper.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[Paper.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[Paper.jar:git-Paper-455]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[Paper.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[Paper.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[Paper.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[Paper.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[Paper.jar:git-Paper-455]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at com.massivecraft.massivecore.util.Txt.getNicedEnum(Txt.java:436) ~[?:?]
	at com.massivecraft.massivecore.util.Txt.getMaterialName(Txt.java:441) ~[?:?]
	at com.massivecraft.creativegates.MaterialCountUtil.desc(MaterialCountUtil.java:51) ~[?:?]
	at com.massivecraft.creativegates.EngineMain.tools(EngineMain.java:411) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1016.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[Paper.jar:git-Paper-455]
	... 17 more
`
