### ISSUE TITLE
PlayerMoveEvent/PlayerInteractEvent buggs

### ISSUE THREAD

**Issue by Jorit34** [MassiveCraft/CreativeGates#94]
If I set up 2 portals on the Network "Test" with 2 clocks, if I stand in them they won't tp me, and I keep getting this error.. Can someone help? I tried everything.. Thanks already.

(http://pastebin.com/aP64iyBi)

[19:18:25] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to CreativeGates v2.6.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:236) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.PacketPlayInFlying.a(SourceFile:137) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.PacketPlayInPositionLook.handle(SourceFile:20) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:157) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(SourceFile:134) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:667) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
Caused by: java.lang.NullPointerException
        at com.massivecraft.creativegates.NetworkIdEqualsPredictate.apply(NetworkIdEqualsPredictate.java:31) ~[?:?]
        at com.massivecraft.creativegates.NetworkIdEqualsPredictate.apply(NetworkIdEqualsPredictate.java:1) ~[?:?]
        at com.massivecraft.massivecore.store.MStoreUtil.uglySQL(MStoreUtil.java:25) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.getAll(Coll.java:142) ~[?:?]
        at com.massivecraft.creativegates.entity.UGateColl.getGateChain(UGateColl.java:61) ~[?:?]
        at com.massivecraft.creativegates.entity.UGate.getGateChain(UGate.java:207) ~[?:?]
        at com.massivecraft.creativegates.entity.UGate.transport(UGate.java:178) ~[?:?]
        at com.massivecraft.creativegates.MainListener.useGate(MainListener.java:267) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_51]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_51]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        ... 13 more
[19:18:25] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CreativeGates v2.6.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:225) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:374) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:630) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(SourceFile:60) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(SourceFile:9) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:157) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(SourceFile:134) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:667) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
Caused by: java.lang.NullPointerException
        at com.massivecraft.creativegates.NetworkIdEqualsPredictate.apply(NetworkIdEqualsPredictate.java:31) ~[?:?]
        at com.massivecraft.creativegates.NetworkIdEqualsPredictate.apply(NetworkIdEqualsPredictate.java:1) ~[?:?]
        at com.massivecraft.massivecore.store.MStoreUtil.uglySQL(MStoreUtil.java:25) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.getAll(Coll.java:142) ~[?:?]
        at com.massivecraft.creativegates.entity.UGateColl.getGateChain(UGateColl.java:61) ~[?:?]
        at com.massivecraft.creativegates.entity.UGate.getGateChain(UGate.java:207) ~[?:?]
        at com.massivecraft.creativegates.MainListener.tools(MainListener.java:568) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_51]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_51]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[craftbukkit-1.7.10-dev.jar:git-Bukkit-1.7.9-R0.2-16-g37c7969-b3105jnks]
        ... 15 more
[19:18:25] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to CreativeGates v2.6.0

**Comment by oloflarsson** [comment]
I have never had this issue on my own server. I think your database might be damaged. Find the gate without a network id and delete it manually from your database.
